Repository synthesized-io/fairlens, pull requests merged in 2021-09, with the labels that each got.

#116 Add Sonarcloud Action
  .github/workflows/ci.yml
  README.md
  sonar-project.properties
Labels: type:maintenance, priority:medium

#126 Add CODE_OF_CONDUCT.md
  .github/CODE_OF_CONDUCT.md
Labels: category:repository-maintainance

#130 Remove old templates and tweak new templates.
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue.yml
Labels: type:maintenance

#131 add codecov.yml
  .github/workflows/ci.yml
  README.md
  codecov.yml
Labels: type:maintenance

#125 Statistical analysis
  docs/index.rst
  docs/user_guide/index.rst
  notebooks/compas.ipynb
  src/fairlens/metrics/significance.py
  src/fairlens/metrics/statistics.py
  src/fairlens/scorer.py
  tests/test_scorer.py
  tests/test_significance.py
  tests/test_statistics.py
Labels: category:bias-measurement, category:fairness-scoring, type:feature

#119 Update attribute plots for binary variables
  .github/workflows/ci.yml
  src/fairlens/plot/distr.py
  tests/test_plot.py
Labels: type:enhancement
