Repository synthesized-io/fairlens, pull requests merged in 2021-08, with the labels that each got.

#92 Fix readthedocs config file
  .readthedocs.yaml
Labels: type:bug

#93 Add google-analytics id
  docs/conf.py
Labels: category:documentation

#88 Update contribution guidelines
  .github/CONTRIBUTING.md
Labels: category:documentation

#98 Add Colab badge
  README.md
Labels: category:repository-maintainance

#102 Add dependabot
  .github/dependabot.yml
Labels: category:repository-maintainance

#114 Use logo with white background
  README.md
  docs/_static/FairLens_759x196.png
Labels: type:documentation
